### ISSUE TITLE
Add cloud connectivity settings REST endpoint: `api/v1/ccs`

### ISSUE THREAD

**Issue by microbuilder** [Linaro/lite_bootstrap_server#31]
Added a new endpoint to the REST API to return the current cloud connectivity
settings for clients, based on the selected cloud service (`azure-cli`, etc.)
used by LinaroCA to register new devices in the cloud.

## `/api/v1/ccs` Cloud Connectivity Settings Request: **GET**

Request a **CBOR** (`application/cbor`) or **JSON** (`application/json`) dataset
containing required fields to enable connecting to the cloud provider used for
device registration in `/api/c1/cr` and `/api/v1/p10cr`.

The response contents will vary based on the cloud API used by LinaroCA.
`azure-cli` will return Azure IoT Hub settings, etc.

### Requirements

- A timestamp indicating when this data was last updated, to know if there has
  been an update to the cloud server settings.

**Comment by microbuilder** [comment]
@d3zd3z We had discussed earlier returning this data on device registration, but having a dedicate endpoint might be better since it also gives us a mechanism to update it at a later date in case something changes.

**Comment by d3zd3z** [comment]
Maybe both, or just include this nested structure within the result for the registration request.

**Comment by microbuilder** [comment]
Having a separate endpoint gives us an easy update mechanism for devices that have already registered a cert, but where the connection details might have changed post registration.
